name: menu
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.3
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
  - assets/imagen.png
  - assets/menu.png
  - assets/pastas.png
  - assets/sedes.png
  - assets/factural.png
  - assets/logoPicadas.png
  - assets/lomejor.png
<<<<<<< HEAD
  - assets/Ubicacion 1.png
  - assets/Ubicacion 2.png
  - assets/Ubicacion 3.png
=======
  - assets/loguito.png
  - assets/login.png
  - assets/tradicionales.png
  - assets/arma.png
  - assets/sedesi.png
  - assets/sugerencias.png
  - assets/registro.png
>>>>>>> 721fce55db0d06d27c05b6c60dca6240aad7a729

  fonts:
  - family: Gagaline
    fonts:
      - asset: fonts/Gagalin-Regular.otf


  

  

  
